inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - gemfiles/vendor/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 512

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/AsciiComments:
  Enabled: false
